global using AutoMapper;
global using AutoMapper.QueryableExtensions;
global using Backend.Configuration;
global using Backend.Src.Api.Helpers;
global using Backend.Src.Api.Middleware;
global using Backend.Src.Api.Models;
global using Backend.Src.Api.Models.Request;
global using Backend.Src.Api.Models.Response;
global using Backend.Src.Application.DTOs;
global using Backend.Src.Application.Interfaces;
global using Backend.Src.Application.Mappings;
global using Backend.Src.Application.Models;
global using Backend.Src.Application.Queries;
global using Backend.Src.Application.Queries.Providers;
global using Backend.Src.Application.Queries.Strategies;
global using Backend.Src.Application.Services;
global using Backend.Src.Domain.Entities;
global using Backend.Src.Domain.Enums;
global using Backend.Src.Domain.ValueObjects;
global using Backend.Src.Infrastructure;
global using Backend.Src.Infrastructure.Persistence.Seed;
global using Backend.Src.Infrastructure.Services;
global using CloudinaryDotNet;
global using CloudinaryDotNet.Actions;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Options;
global using Microsoft.Net.Http.Headers;
global using Microsoft.OpenApi.Models;
global using Serilog;
global using Serilog.Events;
global using Stripe;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Linq.Expressions;
global using System.Net;
global using System.Security.Claims;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using Account = CloudinaryDotNet.Account;
global using File = System.IO.File;
global using IConfigurationProvider = AutoMapper.IConfigurationProvider;
global using ILogger = Microsoft.Extensions.Logging.ILogger;
global using ProductService = Backend.Src.Application.Services.ProductService;
global using Backend.Src.Application.Queries.Interfaces;
global using System.Collections;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.IdentityModel.Tokens;
global using System.Text;
global using Microsoft.AspNetCore.Authorization;
global using AccountService = Backend.Src.Application.Services.AccountService;
global using Backend.Src.Infrastructure.Repositories;
global using Swashbuckle.AspNetCore.SwaggerGen;


